# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19uM2EXPyULFhJy7x6Af08twVlcqRBMz5
"""

class Human:
    def __init__(self, name, age):
        self.name = name
        self.age  = age

    def printinfo(self):
        print(self.name)
        print(self.age)

User = Human("Taro", 25)

User.printinfo()