# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/127o2E2YDCLxkB84FYk-dr_lEc-mV94j9
"""

zyohen = 10
kahen = 20
height = 5
Surface = (zyohen + kahen) * height / 2
print(f"{Surface}cm²")