# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19uM2EXPyULFhJy7x6Af08twVlcqRBMz5
"""

class Human:
    def __init__(self, name, age):
      self.name = name
      self.age  = age

    def check_adult(self):
      if self.age >= 20:
         print("adult")
      else:
         print("child")

Tanaka = Human("Tanaka",20)
Yamada = Human("Yamada",14)
Takagi = Human("Takagi",34)

Tanaka.check_adult()
Yamada.check_adult()
Takagi.check_adult()

