# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19uM2EXPyULFhJy7x6Af08twVlcqRBMz5
"""

list = ["水","金","地","火","木","土","天","海","冥"]
for comet in list:
    print(comet)

i = 0
while i != 9:
    print(list[i])
    i = i+1